export {
  listSidebarProjects,
  updateProject,
  changeProjectChat,
} from "./v1-http.js";
export {
  bearerCredentials,
  cookieCredentials,
  detectBrowserCredentials,
  engineCapabilityFromHash,
  engineCredentials,
  type CredentialAdapter,
  type CredentialKind,
} from "./credentials.js";
export {
  resolveGuiSessionUrl,
  resolveHttpOrigin,
  resolveHttpUrl,
  resolveV2SessionUrl,
  V2_SESSION_PATH,
  V2_SESSION_SUBPROTOCOL,
  type ClientLocation,
} from "./origin.js";
export {
  readErrorMessage,
  requestJson,
  type ClientFetch,
  type ClientResponse,
  type HttpClientOptions,
} from "./http.js";
export {
  addNvidiaModel,
  addZeroCostModel,
  browserHttpClient,
  checkFrame,
  createHttpClient,
  createProject,
  EMPTY_MEMORY_FILTERS,
  executeShellCommand,
  formatShellHostResult,
  generateImage,
  generatedImageLocatorSrc,
  generatedImageSrc,
  listProjects,
  loadKieCatalog,
  loadMcpHealth,
  loadMcpServers,
  loadMemory,
  loadModels,
  loadNvidiaCatalog,
  loadProviderSettings,
  loadRuntimeCapabilities,
  loadZeroCostCatalog,
  refreshZeroCostCatalog,
  openProject,
  previewProject,
  probeMcpServer,
  registerExistingProject,
  saveMcpServers,
  saveProviderSettings,
  SHELL_ENDPOINT,
  uploadSource,
  uploadSourcePath,
  UPLOAD_ENDPOINT,
  type MemoryFilters,
  type UploadableFile,
} from "./v1-http.js";
export { createGuiSessionClient, type GuiSessionClient } from "./v1-session.js";
export {
  DEFAULT_GUI_MODEL,
  type GuiSession,
  type GuiSessionClientOptions,
  type GuiSessionState,
  type GuiSessionStatus,
  type GuiWebSocket,
  type GuiWebSocketConstructor,
  type GuiWebSocketEvent,
  type PromptImageAttachment,
  type RuntimeToolCall,
  type RuntimeToolStatus,
  type SessionControl,
  type SessionSnapshot,
  type ToolPermissionDecision,
} from "./session-types.js";
export {
  issueV2Ticket,
  loadV2Info,
  lookupV2CommandReceipt,
  V2ClientError,
} from "./v2-http.js";
export {
  createPlatformV3Client,
  PlatformV3ClientError,
  type PlatformV3Client,
  type PlatformV3ClientErrorCode,
  type PlatformV3ClientOptions,
  type PlatformV3Conversation,
  type PlatformV3ConversationCreateRequest,
  type PlatformV3ConversationListResponse,
  type PlatformV3ConversationResponse,
  type PlatformV3EventsQuery,
  type PlatformV3EventsResponse,
  type PlatformV3Info,
  type PlatformV3Run,
  type PlatformV3RunCancelRequest,
  type PlatformV3RunCreateRequest,
  type PlatformV3RunCreateResponse,
  type PlatformV3RunResponse,
} from "./platform-v3.js";
export {
  createV2SessionClient,
  type V2SessionClient,
  type V2SessionClientOptions,
  type V2SessionView,
} from "./v2-session.js";
export {
  CLIENT_MESSAGE_KEYS,
  DEFAULT_GUI_HOST,
  encodeClientMessage,
  GUI_SESSION_PATH,
  GuiHostProtocolError,
  parseServerMessage,
  type ClientMessage,
  type ServerMessage,
} from "@a008/protocol";
