/** Current v1 surface, descriptive only: it does not grant capabilities or route requests. */
export const v1HttpRoutes = [
  ["GET", "/health", "public health", "server"],
  ["POST", "/auth/login", "standalone PIN exchange when enabled", "pin-auth"],
  ["GET", "/v1/models", "host model catalog", "provider-routes"],
  [
    "GET",
    "/v1/memory",
    "current bridge project / fixed panel session",
    "ACP inspection",
  ],
  ["GET", "/v1/browser/frame-check", "host network probe", "browser-frame"],
  ["GET", "/v1/catalog/kie", "host catalog", "provider-routes"],
  ["GET", "/v1/mcp-servers", "host MCP configuration", "provider-routes"],
  [
    "POST",
    "/v1/mcp-servers",
    "host MCP configuration mutation",
    "provider-routes",
  ],
  [
    "GET",
    "/v1/catalog/zero-cost",
    "bundled validated zero-cost model discovery",
    "zero-cost-catalog",
  ],
  [
    "POST",
    "/v1/catalog/zero-cost",
    "explicit published ZeroCostRadar update check",
    "zero-cost-catalog",
  ],
  [
    "POST",
    "/v1/catalog/zero-cost/models",
    "revalidated ZeroCostRadar model registration",
    "provider-routes",
  ],
  ["GET", "/v1/catalog/nvidia", "host upstream catalog", "provider-routes"],
  ["POST", "/v1/catalog/nvidia", "host catalog mutation", "provider-routes"],
  ["DELETE", "/v1/catalog/nvidia", "host catalog mutation", "provider-routes"],
  [
    "GET",
    "/v1/provider-settings",
    "host configuration; no credential values",
    "provider-routes",
  ],
  [
    "POST",
    "/v1/provider-settings",
    "host credential/configuration mutation",
    "provider-routes",
  ],
  [
    "POST",
    "/v1/images",
    "host provider job and source store",
    "provider-routes",
  ],
  ["GET", "/v1/blobs/{sha256}/{name}", "host source store", "source-store"],
  ["GET", "/v1/projects", "host project registry", "project-routes"],
  [
    "GET",
    "/v1/projects/browse",
    "host absolute filesystem path",
    "project-routes",
  ],
  ["POST", "/v1/projects/preview", "host bootstrap preview", "project-routes"],
  [
    "POST",
    "/v1/projects/bootstrap",
    "host bootstrap + global workspace switch",
    "project-routes",
  ],
  [
    "POST",
    "/v1/projects/register",
    "host existing-project registration + global workspace switch",
    "project-routes",
  ],
  [
    "POST",
    "/v1/projects/open",
    "host global workspace switch",
    "project-routes",
  ],
  ["POST", "/v1/shell", "current host cwd; explicit user shell", "terminal"],
  [
    "POST",
    "/v1/upload",
    "host source store + current bridge ingest",
    "source-store / ACP",
  ],
  [
    "GET/HEAD",
    "/{asset}",
    "static assets; root PIN login page when enabled",
    "server",
  ],
] as const;
