export const KNOWLEDGE_RELATION_TYPE_RULES = [
  "Classify semantic relation as exactly one of: new, restatement, extend, supersede, or conflict.",
  "Judge the truth-bearing semantics of the proposal against the supplied candidates. Do not classify from lexical overlap, shared entities, tags, domains, authority, confidence, provenance source type or activation status.",
  "restatement means semantic equivalence: the same predicate/relationship, arguments, value, polarity, quantity or quantifier, modality, scope, relevant time and material qualifications. A proposal is not a restatement merely because most words, entities or numbers overlap.",
  "Changes such as every frame versus every 30th frame, all members versus one member, may versus does, or zero page versus RODATA are material semantic changes, not restatements.",
  "A narrower statement is not automatically a restatement of a broader compound statement. If omitted or changed parts could independently differ in truth, compare the independently asserted semantic content instead of treating textual overlap as equivalence.",
  "extend means compatible additional knowledge that can hold simultaneously with the target and does not replace a value at the same semantic address.",
  "Do not use extend for a changed value of the same attribute or relationship slot.",
  "supersede means the proposal supplies an updated or corrected applicable value/assertion for the same semantic address or state-bearing subject and therefore replaces the prior applicable value in Current State.",
  "An explicit correction of an earlier present/current value is supersede, even when the corrected statement shares most of its wording with the target.",
  "correction is not a sixth wire relation type. Express a directed current-value correction as supersede; deterministic reconciliation owns correction/history bookkeeping.",
  "conflict means the assertions are materially incompatible under the same relevant entity, scope, time and qualifications, but the semantic content does not establish a directed update/correction relationship.",
  "Do not choose conflict because one source has lower authority, lower confidence, weaker provenance or no verbatim support. Source/support metadata does not decide which semantic relation exists.",
  "new means independent knowledge for which none of the other four semantic relations is established.",
  "When structuredProposition is present, use it as source-grounded comparison structure. For attribute_binding with the same entityLabel and attribute, equal values strongly indicate restatement; a different asserted current value indicates supersede when the proposal is an update/correction, otherwise conflict. Never ignore a changed value because the surrounding prose is similar.",
  "When structured propositions resolve to different semantic addresses, do not force restatement or supersede merely because the prose is similar.",
  "Historical/future applicability and final HEAD ownership are runtime reconciliation concerns. Never infer current truth from activationStatus, confidence, authority, retrieval rank or source type.",
  "Candidates may include historical, dormant or non-HEAD evidence needed for comparison. Do not assume every supplied candidate is Current State; classify semantic relation only and leave HEAD resolution to runtime reconciliation.",
  "The classifier describes semantic relation only. It does not decide canonical IDs, persistence, lifecycle strength, activation, decay, attraction, commit order or final HEAD ownership.",
] as const;

export const KNOWLEDGE_ASSOCIATION_RULES = [
  "When associationContext exists, associations may contain fromHandle, toHandle, relation, supportsRelation, and optional support with source/start/end.",
  "Use only candidate handles, entity handles supplied in associationContext.entities, or proposal for the proposal claim. Never invent endpoints.",
  "Preserve direction. Reuse the exact existing relation type for the same semantic relation and scope; a genuinely new semantic relation may use a concise snake_case type.",
  "Association support is independent of claim relation classification. Set supportsRelation true only when a non-empty UTF-16 span in the ORIGINAL associationContext.source.content affirmatively establishes that precise relation between both endpoints.",
  "The support source must match associationContext.source.origin. Proposal/candidate text, model answer, retrieved context and graph are not new source evidence.",
  "Questions, unsupported quotations, hypothetical/instruction text, echoes, co-occurrence, shared domain/topic, display links, provenance links and structural claim-entity membership are not semantic associations.",
  "Do not output attraction or numeric strength. Association persistence, attraction updates and lifecycle remain runtime-owned and are driven by actual retrieval/use signals, not by this semantic classifier.",
] as const;
